config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :book_instances do
    member do
      get 'lending'
      post 'lend'
      post 'return'
      post 'reserve'
      post 'dereserve'
    end
  end
  resources :users
  resources :authors
  resources :books
  resources :publishers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_instance.rb
class BookInstance < ApplicationRecord
  before_save :reset_after_return, :handle_lending

  belongs_to :book
  has_one :reserved_by
  has_one :lended_by

  validates :purchased_at, :shelfmark, :book_id, presence: { message: "ist ein Pflichtfeld!"}
  validate :ensure_lender_not_blocked


  public def clear_lender_for_blocked
    self.lended_by_id = nil
  end

  def lender
    User.find(self.lended_by_id) if !self.lended_by_id.blank? 
  end

  def reserver
    User.find(self.reserved_by_id) if !self.reserved_by_id.blank? 
  end
  
	def is_overdue
		!!due_at&.to_date&.past?
	end

  def ensure_lender_not_blocked
    if !self.lender.nil? and self.lender.blocked
      errors.add(:base, "Der User kann das Buch nicht ausleihen, er ist blockiert!")
      self.update(lended_by_id: nil)
    end
  end

  def set_checkout_date
      if !self.lended_by_id.blank?

        if !self.returned_at.blank?
          self.returned_at = nil
        end

        if self.checkout_at.blank?
          self.checkout_at = Time.now
        end
        
      end
  end

  def set_returned_at
      if self.lended_by_id.blank? and self.returned_at.blank?
        self.returned_at = Time.now
      end
  end

  def reset_after_return
      if (!self.returned_at.blank? and self.returned_at_was == nil) or self.lended_by_id.blank?
        self.due_at = nil
        self.checkout_at = nil
        self.lended_by_id = nil

        if self.returned_at.blank?
          self.returned_at = Time.now
        end
      end
  end

  def handle_lending 
    if !self.lended_by_id.blank? and self.lended_by_id_changed?
      self.returned_at = nil
      self.checkout_at = Time.now
      self.due_at = self.due_at || 4.weeks.from_now
    end
  end

  def self.custom_select(filter, current_user)
    book_instances = BookInstance.order('created_at desc')

    case filter
    when 'lendable'
        book_instances = book_instances.select {|b| !b.lender and !b.reserver }
    when 'reserved'
        book_instances = book_instances.select {|b| !!b.reserver }
    when 'lended'
        book_instances = book_instances.select {|b| !!b.lender }
    when 'overdue'
        book_instances = book_instances.select {|b| b.is_overdue }
    when 'lended_by_current_user'
        book_instances = book_instances.select {|b| !!b.lender && b.lender.id == current_user.id } unless current_user.nil?
    when 'reserved_by_current_user'
        book_instances = book_instances.select {|b| !!b.reserver && b.reserver.id == current_user.id } unless current_user.nil?
    end

    return book_instances
  end  

end

app/controllers/book_instances_controller.rb
class BookInstancesController < ApplicationController
  before_action :set_book_instance, only: %i[ show edit lending update destroy lend reserve return dereserve ]
  before_action :validate_user_session, only: %i[ lending edit update destroy ]

  # GET /book_instances or /book_instances.json
  def index
    case params[:filter]
    when 'lendable'
      @filter_name = "ausleihbar"
    when 'reserved'
      @filter_name = "reserviert"
    when 'lended'
      @filter_name = "geliehen"
    when 'overdue'
      @filter_name = "überfällig"
    when 'reserved_by_current_user'
      @filter_name = "meine reservierten Bücher"
    when 'lended_by_current_user'
      @filter_name = "meine geliehenen Bücher"
    end
    @book_instances = BookInstance.custom_select(params[:filter], current_user)
  end

  # GET /book_instances/1 or /book_instances/1.json
  def show
  end

  # GET /book_instances/new
  def new
    @book_instance = BookInstance.new
  end

  # GET /book_instances/1/edit
  def edit
  end

  # GET /book_instances/1/lending
  def lending
  end

  
  # POST /book_instances/1/lend
  def lend
    if user_signed_in? and (@book_instance.lender.blank? or current_user.admin?)
      @book_instance.update(lended_by_id: current_user.id)
    end
    head 200
  end
  
  # POST /book_instances/1/return
  def return
    if user_signed_in? and (@book_instance.lender&.id == current_user.id or current_user.admin?)
      @book_instance.update(lended_by_id: nil)
    end
    head 200
  end
  
  # POST /book_instances/1/reserve
  def reserve
    if user_signed_in? and (@book_instance.reserver.blank? or current_user.admin?)
      @book_instance.update(reserved_by_id: current_user.id)
    end
    head 200
  end
  
  # POST /book_instances/1/dereserve
  def dereserve
    if user_signed_in? and (@book_instance.reserver&.id == current_user.id or current_user.admin?)
      @book_instance.update(reserved_by_id: nil)
    end
    head 200
  end

  # POST /book_instances or /book_instances.json
  def create
    @book_instance = BookInstance.new(book_instance_params)

    @book_instance.errors.add(:base, "Diese Aktion ist nicht erlaubt!") unless user_signed_in?

    respond_to do |format|
      if user_signed_in? and @book_instance.save
        format.html { redirect_to @book_instance, notice: "Buchexemplar wurde erfolgreich erzeugt." }
        format.json { render :show, status: :created, location: @book_instance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_instances/1 or /book_instances/1.json
  def update
    if user_signed_in? and @book_instance.update(book_instance_params)
      respond_to do |format|
        format.html { redirect_to @book_instance, notice: "Buchexemplar wurde erfolgreich aktualisiert." }
        format.json { render :show, status: :ok, location: @book_instance }
      end
    else
      if request.referer.split('/').last == "edit"
        respond_to do |format|
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @book_instance.errors, status: :unprocessable_entity }
        end
      else        
        respond_to do |format|
          format.html { render :lending, status: :unprocessable_entity }
          format.json { render json: @book_instance.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /book_instances/1 or /book_instances/1.json
  def destroy
    if user_signed_in?
        @book_instance.destroy
      respond_to do |format|
        format.html { redirect_to book_instances_url, notice: "Buchexemplar wurde erfolgreich gelöscht." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_instance
      @book_instance = BookInstance.find(params[:id])
    end

    # only let admin pass, regular users must use the one-click-lending and reserving
    def validate_user_session
      if !current_user&.admin?
        @book_instance.errors.add(:base, "Diese Aktion ist nicht erlaubt!")
        respond_to do |format|
          format.html { render :show, status: :unprocessable_entity }
          format.json { render json: @book_instance.errors, status: :unprocessable_entity }
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def book_instance_params
      params.require(:book_instance).permit(:book_id, :shelfmark, :purchased_at, :lended_by_id, :reserved_by_id, :checkout_at, :due_at, :returned_at)
    end
end

app/helpers/book_instances_helper.rb
module BookInstancesHelper
end

app/views/book_instances/_form.html.haml
= form_for @book_instance do |f|
  = render 'components/error', errors: @book_instance.errors

  %table.table.table-striped
    %tr.form-group
      %td= f.label :book_id, "Buchtitel", class: "control-label"
      %td= f.select :book_id, options_from_collection_for_select(Book.all, "id", "title", @book_instance.book_id), {}, {class: "form-control searchselect", :data => {"live-search": "true"}}
    %tr.form-group
      %td= f.label :shelfmark, "Regal", class: "control-label"
      %td= f.text_field :shelfmark, class: "form-control"
    %tr.form-group
      %td= f.label :purchased_at, "Einkaufsdatum", class: "control-label"
      %td= f.date_field :purchased_at, class: "form-control"
    %tr
      %td
      %td= f.submit "Speichern", class: "btn btn-success"

app/views/book_instances/_form_lending.html.haml
= form_for @book_instance do |f|
  = render 'components/error', errors: @book_instance.errors

  %table.table.table-striped
    %tr.form-group
      %td= f.label nil, "Buchtitel", class: "control-label"
      %td= f.text_field nil, class: "form-control", value: @book_instance.book.title, disabled:true
    %tr.form-group
      %td= f.label nil, "Regal", class: "control-label"
      %td= f.text_field nil, class: "form-control", value: @book_instance.shelfmark, disabled:true
    %tr.form-group
      %td= f.label :lended_by_id, "Ausgeliehen von", class: "control-label"
      %td= f.select :lended_by_id, options_from_collection_for_select(User.all, "id", "full_name", @book_instance.lended_by_id.nil? ? '' : @book_instance.lended_by_id), {include_blank: true}, {class: "form-control searchselect", :data => {"live-search": "true"}}
    %tr.form-group
      %td= f.label :reserved_by_id, "Reserviert von", class: "control-label"
      %td= f.select :reserved_by_id, options_from_collection_for_select(User.all, "id", "full_name", @book_instance.reserved_by_id.nil? ? '' : @book_instance.reserved_by_id), {include_blank: true}, {class: "form-control searchselect", :data => {"live-search": "true"}}
    -#%tr.form-group
      %td= f.label nil, "Geliehen am", class: "control-label"
      %td= f.datetime_field :checkout_at, class: "form-control", :value => @book_instance.checkout_at&.strftime("%FT%H:%M")
    %tr.form-group
      %td= f.label nil, "Rückgabefrist bis", class: "control-label"
      %td= f.date_field :due_at, class: "form-control"
    -#%tr.form-group
      %td= f.label nil, "Rückgabe am", class: "control-label"
      %td= f.datetime_field :returned_at, class: "form-control", :value => @book_instance.returned_at&.strftime("%FT%H:%M")
    %tr
      %td
      %td= f.submit "Speichern", class: "btn btn-success"

app/views/book_instances/edit.html.haml
.panel.slim.panel-default
  .panel-heading
    %h3
      Buchexemplar bearbeiten
  = render 'form'

= link_to @book_instance, class: "button btn btn-warning" do
  =material_icon.arrow_back 
  Abbrechen
= link_to lending_book_instance_path(@book_instance), class: "button btn" do
  =material_icon.person
  Leihstatus setzen
= link_to book_instances_path, class: "button btn btn-default" do
  =material_icon.format_list_bulleted 
  Liste

app/views/book_instances/index.html.haml
.panel.panel-default
  .panel-heading
    %h3
      Buchbestand
      %span.small
        = @filter_name
      %span.badge= @book_instances.length
  %table.dataTable.table.table-striped
    %thead
      %tr
        %th Buchtitel
        %th Regal
        %th Einkaufsdatum
        %th Geliehen von
        %th Reserviert von
        %th Ausgeliehen am
        %th Rückgabefrist bis
        %th Rückgabe am
        %th{ "data-orderable": "false" }

    %tbody
      - @book_instances.each do |book_instance|
        %tr
          %td= link_to book_instance.book.title, book_instance.book
          %td= book_instance.shelfmark
          =td_date(book_instance.purchased_at, false)
          %td
            - if !book_instance.lender.blank?
              - if current_user&.admin?
                = link_to book_instance.lender.full_name, book_instance.lender
              - elsif user_signed_in?
                = book_instance.lender.short_name
              - else
                ***
            - else
              \-
          %td
            - if !book_instance.reserver.blank?
              - if current_user&.admin?
                = link_to book_instance.reserver.full_name, book_instance.reserver
              - elsif user_signed_in?
                = book_instance.reserver.short_name
              - else
                ***
            - else
              \-
          =td_date(book_instance.checkout_at)
          =td_date(book_instance.due_at, false)
          =td_date(book_instance.returned_at)
          %td
            .btn-group
              = link_to material_icon.open_in_new, book_instance, class: "button btn btn-default"
              = render 'components/lend_onebutton', bookinstance: book_instance
              - if current_user&.admin?
                = link_to material_icon.edit, edit_book_instance_path(book_instance), class: "button btn btn-warning"
                = link_to material_icon.delete, book_instance, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class: "button btn btn-danger"

%br


- if current_user&.admin?
  = link_to new_book_instance_path, class: "button btn btn-info" do
    =material_icon.add 
    Neues Buchexemplar

app/views/book_instances/lending.html.haml
.panel.slim.panel-default
  .panel-heading
    %h3
      Leihstatus setzen
  = render 'form_lending'

= link_to @book_instance, class: "button btn btn-warning" do
  =material_icon.arrow_back 
  Abbrechen
= link_to book_instances_path, class: "button btn btn-default" do
  =material_icon.format_list_bulleted 
  Liste

app/views/book_instances/new.html.haml
.panel.slim.panel-default
  .panel-heading
    %h3
      Neues Buchexemplar
  = render 'form'

= link_to book_instances_path, class: "button btn btn-warning" do
  =material_icon.arrow_back 
  Abbrechen

app/views/book_instances/show.html.haml
.panel.slim.panel-default
  .panel-heading
    %h3
      Buchexemplar
  %table.table.table-striped
    %tr
      %td Buchtitel:
      %td= link_to @book_instance.book.title, @book_instance.book
    %tr
      %td Regal:
      %td= @book_instance.shelfmark
    %tr
      %td Einkaufsdatum:
      %td= @book_instance.purchased_at&.strftime("%d.%m.%Y")
    %tr
      %td Ausgeliehen von:
      -# TODO Names only for admin visible
      %td
        - if !@book_instance.lender.blank?
          - if current_user&.admin?
            = link_to @book_instance.lender.full_name, @book_instance.lender
          - elsif user_signed_in?
            = @book_instance.lender.short_name
          - else
            %i ***
        - else
          %i Nicht ausgeliehen
    %tr
      %td Reserviert von:
      -# TODO Names only for admin visible
      %td
        - if !@book_instance.reserver.blank?
          - if current_user&.admin?
            = link_to @book_instance.reserver.full_name, @book_instance.reserver
          - elsif user_signed_in?
            = @book_instance.reserver.short_name
          - else
            %i ***
        - else
          %i Nicht reserviert
    %tr
      %td Geliehen am:
      %td= @book_instance.checkout_at&.strftime("%d.%m.%y %H:%M")
    %tr
      %td Rückgabefrist bis:
      %td= @book_instance.due_at&.strftime("%d.%m.%y")
    %tr
      %td Rückgabe am:
      %td= @book_instance.returned_at&.strftime("%d.%m.%y %H:%M")

%br

= render 'components/lend_onebutton', bookinstance: @book_instance, withtext: true

- if current_user&.admin?
  = link_to lending_book_instance_path(@book_instance), class: "button btn" do
    =material_icon.person
    Leihstatus setzen
  = link_to edit_book_instance_path(@book_instance), class: "button btn btn-warning" do
    =material_icon.edit 
    Bearbeiten
  = link_to @book_instance, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class: "button btn btn-danger" do
    =material_icon.delete
    Löschen
= link_to book_instances_path, class: "button btn btn-default" do
  =material_icon.arrow_back 
  Zurück